### ISSUE TITLE
[Bug]: run bvt on ci occurs null rather than Duplicate entry.

### ISSUE THREAD

**Issue by Ariznawlll** [matrixorigin/matrixone#10891]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):
- Hardware parameters:
- OS type:
- Others:

on ci test
```

### Actual Behavior

<img width="1016" alt="image" src="https://github.com/matrixorigin/matrixone/assets/108530700/8c0910fe-e070-4e3c-83c1-1683bfd29728">

https://github.com/matrixorigin/matrixone/actions/runs/5679177059/job/15390863028?pr=10884

wrong case path: /matrixone/test/distributed/cases/pessimistic_transaction/unique_secondary_index.sql

### Expected Behavior

Duplicate entry '2013-01-01 12:00:00' for key '__mo_index_idx_col'

**Comment by zhangxu19830126** [comment]
fixed by #10900

**Comment by Ariznawlll** [comment]
https://github.com/matrixorigin/matrixone/actions/runs/5725725458/job/15514763237?pr=10917
The bug in ci test is still exists.

**Comment by dongdongyang33** [comment]
no progress

**Comment by dongdongyang33** [comment]
no progress

**Comment by ouyuanning** [comment]
还没时间看

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on this

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by ouyuanning** [comment]
not working on it

**Comment by jensenojs** [comment]
https://github.com/matrixorigin/matrixone/issues/10848 已经提交了相关Pr，短期没有复现，再观察一段时间

**Comment by Ariznawlll** [comment]
短期没有出现！
