### ISSUE TITLE
[Bug]: tpcc 100-100 tpmC decreased very much on Optimistic mode on TKE 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#11235]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): ec91a30
- Hardware parameters:
  2*CN : 16C  64G
  1*DN : 16C  64G
  3*LOG : 4C  16G
- OS type:
- Others:
  MEMCACHE: 12G
  DISKCACHE: 100G
```

### Actual Behavior

job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5869170981/job/15915117435

<img width="1368" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/d42368d3-d4b5-4aa3-a6d0-996e3254be22">

**Comment by triump2020** [comment]
may be caused by  `918bf5ff3bed918b2006f9649ef6e33561916a8a`  .  @LeftHandCold

**Comment by LeftHandCold** [comment]
Fixed in #11240 and #11246. observe another day

**Comment by aressu1985** [comment]
not fixed

job link: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5881148057/job/15950547256

commit: 82cfebd

**Comment by XuPeng-SH** [comment]
assign to @gouhongshen

**Comment by aressu1985** [comment]
update on 8.21
job link:
https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5918356232/job/16049273993

<img width="1411" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/62221757-77da-43b3-bb07-0114f1842a73">

**Comment by gouhongshen** [comment]
it seems can not blame any commits, just unsteady TPCC performance.

have no idea what case such unsteady yet, however, we fund that the lower TPCC result has a lower block read mem cache hit rate, and the higher result has a higher rate.

and the bigger CN memory size has little help with this rate.




CN mem cache: 1G

```YAML
10 warehouse 1 terminal，tpmC = 1000+

"duration: 15000000000, blk hit rate: 39/61=0.639, entry hit rate: 190/516=0.368, blks in each reader: 62/25=2.480"
"duration: 15000000000, blk hit rate: 154/215=0.716, entry hit rate: 1013/1890=0.536, blks in each reader: 215/97=2.216"
"duration: 15000000000, blk hit rate: 348/422=0.825, entry hit rate: 1993/3119=0.639, blks in each reader: 424/302=1.404"
"duration: 15000000000, blk hit rate: 565/646=0.875, entry hit rate: 3153/4379=0.720, blks in each reader: 648/448=1.446"
"duration: 15000000000, blk hit rate: 592/689=0.859, entry hit rate: 3586/4952=0.724, blks in each reader: 692/509=1.360"
"duration: 15000000000, blk hit rate: 592/689=0.859, entry hit rate: 3586/4952=0.724, blks in each reader: 692/509=1.360"
"duration: 15000000000, blk hit rate: 542/614=0.883, entry hit rate: 3231/4345=0.744, blks in each reader: 615/355=1.732"
"duration: 15000000000, blk hit rate: 903/993=0.909, entry hit rate: 5344/6642=0.805, blks in each reader: 994/673=1.477"
"duration: 15000000000, blk hit rate: 1271/1356=0.937, entry hit rate: 7471/8534=0.875, blks in each reader: 1357/947=1.433"
"duration: 15000000000, blk hit rate: 4352/4468=0.974, entry hit rate: 25332/26829=0.944, blks in each reader: 4468/3452=1.294"
"duration: 15000000000, blk hit rate: 13368/13437=0.995, entry hit rate: 77536/78244=0.991, blks in each reader: 13437/10291=1.306"
"duration: 15000000000, blk hit rate: 10182/10206=0.998, entry hit rate: 56376/56720=0.994, blks in each reader: 10206/7881=1.295"

```


```YAML
10 warehouse 10 terminal tpmC = 3000+

"duration: 15000000000, blk hit rate: 158560/159404=0.995, entry hit rate: 2343353/2359513=0.993, blks in each reader: 159396/122778=1.298"
"duration: 15000000000, blk hit rate: 190486/190746=0.999, entry hit rate: 2318050/2320211=0.999, blks in each reader: 190743/147008=1.298"
"duration: 15000000000, blk hit rate: 178617/178864=0.999, entry hit rate: 2002663/2005037=0.999, blks in each reader: 178867/137968=1.296"
"duration: 15000000000, blk hit rate: 173304/173655=0.998, entry hit rate: 1733751/1737112=0.998, blks in each reader: 173656/121503=1.429"
"duration: 15000000000, blk hit rate: 179556/179892=0.998, entry hit rate: 1735571/1738814=0.998, blks in each reader: 179915/123942=1.452"
"duration: 15000000000, blk hit rate: 202929/203165=0.999, entry hit rate: 1874297/1876191=0.999, blks in each reader: 203163/134369=1.512"
"duration: 15000000000, blk hit rate: 204792/205050=0.999, entry hit rate: 1920659/1922712=0.999, blks in each reader: 205052/129310=1.586"

```

```YAML
100 warehouse 10 terminal tpmcC = 100+

"duration: 15000000000, blk hit rate: 80/126=0.635, entry hit rate: 2766/8562=0.323, blks in each reader: 142/114=1.246"
"duration: 15000000000, blk hit rate: 1196/1553=0.770, entry hit rate: 61955/102295=0.606, blks in each reader: 1556/875=1.778"
"duration: 15000000000, blk hit rate: 1525/1963=0.777, entry hit rate: 82575/131909=0.626, blks in each reader: 1965/1224=1.605"
"duration: 15000000000, blk hit rate: 779/1013=0.769, entry hit rate: 47433/75893=0.625, blks in each reader: 1010/634=1.593"
"duration: 15000000000, blk hit rate: 969/1235=0.785, entry hit rate: 51865/83497=0.621, blks in each reader: 1235/787=1.569"
"duration: 15000000000, blk hit rate: 1458/1918=0.760, entry hit rate: 89557/136124=0.658, blks in each reader: 1920/1158=1.658"
"duration: 15000000000, blk hit rate: 1458/1918=0.760, entry hit rate: 89557/136124=0.658, blks in each reader: 1920/1158=1.658"
"duration: 15000000000, blk hit rate: 1908/2466=0.774, entry hit rate: 118004/179139=0.659, blks in each reader: 2467/1601=1.541"
```

CN mem cache 2G

```YAML
100 warehouse 10 terminal tpmcC = 400+

"duration: 15000000000, blk hit rate: 337/456=0.739, entry hit rate: 10765/25670=0.419, blks in each reader: 475/244=1.947"
"duration: 15000000000, blk hit rate: 1593/2128=0.749, entry hit rate: 88024/145693=0.604, blks in each reader: 2129/978=2.177"
"duration: 15000000000, blk hit rate: 2133/2705=0.789, entry hit rate: 115197/180591=0.638, blks in each reader: 2706/1604=1.687"
"duration: 15000000000, blk hit rate: 2019/2507=0.805, entry hit rate: 110882/164968=0.672, blks in each reader: 2509/1515=1.656"
"duration: 15000000000, blk hit rate: 1122/1407=0.797, entry hit rate: 64554/93498=0.690, blks in each reader: 1405/870=1.615"
"duration: 15000000000, blk hit rate: 2152/2633=0.817, entry hit rate: 122791/171756=0.715, blks in each reader: 2635/1687=1.562"
"duration: 15000000000, blk hit rate: 2318/2818=0.823, entry hit rate: 124002/177867=0.697, blks in each reader: 2817/1892=1.489"
"duration: 15000000000, blk hit rate: 2393/2866=0.835, entry hit rate: 124807/170558=0.732, blks in each reader: 2871/1904=1.508"
"duration: 15000000000, blk hit rate: 2868/3406=0.842, entry hit rate: 158521/211841=0.748, blks in each reader: 3407/2356=1.446"
"duration: 15000000000, blk hit rate: 3694/4644=0.795, entry hit rate: 226099/305778=0.739, blks in each reader: 4643/3307=1.404"
"duration: 15000000000, blk hit rate: 16277/20154=0.808, entry hit rate: 867055/1060962=0.817, blks in each reader: 20148/14951=1.348"

```

```YAML
100 warehouse 10 terminal tpmcC = 900+

"duration: 15000000000, blk hit rate: 1149/1378=0.834, entry hit rate: 41391/55160=0.750, blks in each reader: 1378/835=1.650"
"duration: 15000000000, blk hit rate: 7245/8416=0.861, entry hit rate: 284552/369889=0.769, blks in each reader: 8433/5410=1.559"
"duration: 15000000000, blk hit rate: 10758/12386=0.869, entry hit rate: 432255/546678=0.791, blks in each reader: 12391/8620=1.437"
"duration: 15000000000, blk hit rate: 15954/18385=0.868, entry hit rate: 642180/784792=0.818, blks in each reader: 18382/13750=1.337"
"duration: 15000000000, blk hit rate: 21690/25391=0.854, entry hit rate: 811304/985910=0.823, blks in each reader: 25387/20084=1.264"
"duration: 15000000000, blk hit rate: 32035/37725=0.849, entry hit rate: 1099345/1312073=0.838, blks in each reader: 37721/31164=1.210"
"duration: 15000000000, blk hit rate: 40600/48493=0.837, entry hit rate: 1166601/1389299=0.840, blks in each reader: 48493/40569=1.195"
"duration: 15000000000, blk hit rate: 44118/52876=0.834, entry hit rate: 1154974/1374941=0.840, blks in each reader: 52873/44735=1.182"
"duration: 15000000000, blk hit rate: 54857/65371=0.839, entry hit rate: 1220202/1421512=0.858, blks in each reader: 65373/54600=1.197"
"duration: 15000000000, blk hit rate: 9263/10995=0.842, entry hit rate: 143577/167435=0.858, blks in each reader: 10992/9021=1.218"
```

CN mem cache 5G

```YAML
100 warehouse 10 terminal tpmC = 1000+

"duration: 15000000000, blk hit rate: 48801/55307=0.882, entry hit rate: 1093531/1211318=0.903, blks in each reader: 55305/46318=1.194"
"duration: 15000000000, blk hit rate: 56648/64663=0.876, entry hit rate: 887556/979863=0.906, blks in each reader: 64666/54695=1.182"
"duration: 15000000000, blk hit rate: 54074/61669=0.877, entry hit rate: 959854/1060927=0.905, blks in each reader: 61669/51828=1.190"
"duration: 15000000000, blk hit rate: 57128/65707=0.869, entry hit rate: 1006684/1121342=0.898, blks in each reader: 65707/55567=1.182"
"duration: 15000000000, blk hit rate: 61091/69759=0.876, entry hit rate: 1091046/1204378=0.906, blks in each reader: 69759/58923=1.184"
"duration: 15000000000, blk hit rate: 60462/68880=0.878, entry hit rate: 1137906/1258181=0.904, blks in each reader: 68882/58234=1.183"
"duration: 15000000000, blk hit rate: 59951/68358=0.877, entry hit rate: 1198183/1322194=0.906, blks in each reader: 68355/57456=1.190"
"duration: 15000000000, blk hit rate: 59464/68566=0.867, entry hit rate: 1236409/1371007=0.902, blks in each reader: 68569/57847=1.185"
"duration: 15000000000, blk hit rate: 59077/67951=0.869, entry hit rate: 1478936/1638330=0.903, blks in each reader: 67949/57310=1.186"
"duration: 15000000000, blk hit rate: 58956/67326=0.876, entry hit rate: 1509325/1671365=0.903, blks in each reader: 67326/56768=1.186"
"duration: 15000000000, blk hit rate: 57517/66154=0.869, entry hit rate: 1536094/1704098=0.901, blks in each reader: 66156/55479=1.192"

```

**Comment by gouhongshen** [comment]
no progress

**Comment by gouhongshen** [comment]
hit again: https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5953739200/job/16150349746

the cache hit stats of 100w * 100t:

``` YAML
blk hit rate: 427/823=0.5188, entry hit rate: 72986/143347=0.5092, (average) blks in each reader: 881/640=1.3766","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 583/1088=0.5358, entry hit rate: 133167/281055=0.4738, (average) blks in each reader: 1159/676=1.7145","uuid":"31653336-6461-3363-3032-313434623963"}
blk hit rate: 510/735=0.6939, entry hit rate: 89455/166932=0.5359, (average) blks in each reader: 733/409=1.7922","uuid":"39386237-6630-3331-3566-366534613636"}
blk hit rate: 765/1218=0.6281, entry hit rate: 166277/290216=0.5729, (average) blks in each reader: 1224/674=1.8160","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 979/1381=0.7089, entry hit rate: 236052/386991=0.6100, (average) blks in each reader: 1389/687=2.0218","uuid":"31653336-6461-3363-3032-313434623963"}
blk hit rate: 1331/1838=0.7242, entry hit rate: 225916/361808=0.6244, (average) blks in each reader: 1838/987=1.8622","uuid":"39386237-6630-3331-3566-366534613636"}
blk hit rate: 1351/1810=0.7464, entry hit rate: 286157/431545=0.6631, (average) blks in each reader: 1809/1040=1.7394","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 1049/1461=0.7180, entry hit rate: 270337/404325=0.6686, (average) blks in each reader: 1453/791=1.8369","uuid":"31653336-6461-3363-3032-313434623963"}
blk hit rate: 1017/1364=0.7456, entry hit rate: 215574/318778=0.6763, (average) blks in each reader: 1360/826=1.6465","uuid":"39386237-6630-3331-3566-366534613636"}
blk hit rate: 1276/1653=0.7719, entry hit rate: 246403/355700=0.6927, (average) blks in each reader: 1656/1081=1.5319","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 723/1000=0.7230, entry hit rate: 192713/295963=0.6511, (average) blks in each reader: 998/620=1.6097","uuid":"31653336-6461-3363-3032-313434623963"}
blk hit rate: 1479/1932=0.7655, entry hit rate: 290980/440128=0.6611, (average) blks in each reader: 1924/1234=1.5592","uuid":"39386237-6630-3331-3566-366534613636"}
blk hit rate: 1126/1422=0.7918, entry hit rate: 222491/329586=0.6751, (average) blks in each reader: 1406/905=1.5536","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 960/1295=0.7413, entry hit rate: 251633/372708=0.6751, (average) blks in each reader: 1294/824=1.5704","uuid":"31653336-6461-3363-3032-313434623963"}
blk hit rate: 646/815=0.7926, entry hit rate: 110022/172625=0.6373, (average) blks in each reader: 818/578=1.4152","uuid":"39386237-6630-3331-3566-366534613636"}
blk hit rate: 1232/1614=0.7633, entry hit rate: 253532/373919=0.6780, (average) blks in each reader: 1610/1097=1.4676","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 1389/1883=0.7377, entry hit rate: 361665/506588=0.7139, (average) blks in each reader: 1882/1267=1.4854","uuid":"31653336-6461-3363-3032-313434623963"}
blk hit rate: 1978/2491=0.7941, entry hit rate: 412169/563852=0.7310, (average) blks in each reader: 2489/1798=1.3843","uuid":"39386237-6630-3331-3566-366534613636"}
blk hit rate: 1510/1944=0.7767, entry hit rate: 336108/453620=0.7409, (average) blks in each reader: 1954/1379=1.4170","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 1177/1464=0.8040, entry hit rate: 276953/361703=0.7657, (average) blks in each reader: 1458/1065=1.3690","uuid":"31653336-6461-3363-3032-313434623963"}
blk hit rate: 1077/1303=0.8266, entry hit rate: 187676/264295=0.7101, (average) blks in each reader: 1305/942=1.3854","uuid":"39386237-6630-3331-3566-366534613636"}
blk hit rate: 1456/1790=0.8134, entry hit rate: 274085/385274=0.7114, (average) blks in each reader: 1781/1264=1.4090","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 2567/3125=0.8214, entry hit rate: 610184/753748=0.8095, (average) blks in each reader: 3124/2374=1.3159","uuid":"31653336-6461-3363-3032-313434623963"}
blk hit rate: 2171/2598=0.8356, entry hit rate: 453559/564313=0.8037, (average) blks in each reader: 2597/2076=1.2510","uuid":"39386237-6630-3331-3566-366534613636"}
blk hit rate: 1590/1989=0.7994, entry hit rate: 355306/460325=0.7719, (average) blks in each reader: 1985/1536=1.2923","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 1845/2225=0.8292, entry hit rate: 451936/577528=0.7825, (average) blks in each reader: 2233/1779=1.2552","uuid":"31653336-6461-3363-3032-313434623963"}
blk hit rate: 1320/1722=0.7666, entry hit rate: 271136/379247=0.7149, (average) blks in each reader: 1734/1294=1.3400","uuid":"39386237-6630-3331-3566-366534613636"}
blk hit rate: 2004/2470=0.8113, entry hit rate: 349643/444781=0.7861, (average) blks in each reader: 2493/1987=1.2547","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 1321/1695=0.7794, entry hit rate: 295062/390491=0.7556, (average) blks in each reader: 1693/1343=1.2606","uuid":"31653336-6461-3363-3032-313434623963"}
blk hit rate: 2268/2719=0.8341, entry hit rate: 423094/535464=0.7901, (average) blks in each reader: 2701/2058=1.3124","uuid":"39386237-6630-3331-3566-366534613636"}
blk hit rate: 1840/2193=0.8390, entry hit rate: 364830/451951=0.8072, (average) blks in each reader: 2169/1704=1.2729","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 1886/2327=0.8105, entry hit rate: 494770/640323=0.7727, (average) blks in each reader: 2309/1853=1.2461","uuid":"31653336-6461-3363-3032-313434623963"}
blk hit rate: 2591/3082=0.8407, entry hit rate: 480064/620282=0.7739, (average) blks in each reader: 3085/2414=1.2780","uuid":"39386237-6630-3331-3566-366534613636"}
blk hit rate: 3445/4003=0.8606, entry hit rate: 723316/875960=0.8257, (average) blks in each reader: 4024/3283=1.2257","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 1578/2024=0.7796, entry hit rate: 393163/518320=0.7585, (average) blks in each reader: 2039/1617=1.2610","uuid":"31653336-6461-3363-3032-313434623963"}
blk hit rate: 1863/2262=0.8236, entry hit rate: 363793/466001=0.7807, (average) blks in each reader: 2281/1786=1.2772","uuid":"39386237-6630-3331-3566-366534613636"}
blk hit rate: 2660/3154=0.8434, entry hit rate: 479324/597869=0.8017, (average) blks in each reader: 3134/2402=1.3047","uuid":"32663464-6163-6633-3166-323434336264"}
blk hit rate: 2615/3055=0.8560, entry hit rate: 614408/733912=0.8372, (average) blks in each reader: 3053/2461=1.2406","uuid":"31653336-6461-3363-3032-313434623963"}
```

**Comment by gouhongshen** [comment]
no more regression data in the past four days.

**Comment by aressu1985** [comment]
tracking by issue #10509, and this closed
