### ISSUE TITLE
[Bug]: lots of internal error: cn service is not ready and oom after running stability test on standlone mode for 15 hours 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#12263]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):17072178c7b20f344d193c49dd2a4489bbe0a89d
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

after running stability test on standlone mode for 15 hours, there were lots of error for queries:
2023-10-21 23:50:18 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:325 - [UNEXPECTED][TT_NEW_ORDER][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later
Previous DML conflicts with existing constraints or data format. This transaction has to be aborted
2023-10-21 23:50:18 FATAL jTPCCTerminal:212 - [UNEXPECTED][TT_PAYMENT][EXECUTION] ErrorCode : 20101, ErrorMessage : internal error: cn service is not ready, retry later

and at last , the mo was killed by oom

mo-log:
[mo-error.tar.gz](https://github.com/matrixorigin/matrixone/files/13064992/mo-error.tar.gz)

profile:
[profile.tar.gz](https://github.com/matrixorigin/matrixone/files/13064993/profile.tar.gz)

### Steps to Reproduce

```Markdown
1. run a mo server on standlone mode 
2. run bvt test loop
3. run tpch_10 test loop
4. run sysbench mixed test 
5. run tpcc 10 warehouse 10 terminal

or
1.run a mo server on standlone mode
2.git https://github.com/matrixorigin/mo-nightly-regression.git
3. ./stb_test.sh -c /bvtcasepath/

only for linux
```

**Comment by guguducken** [comment]
Also appears in the tke distributed environment. https://github.com/matrixorigin/matrixone/actions/runs/6607668925/job/17945703665

**Comment by aressu1985** [comment]
update on 10.24
mo crash by oom
[Tue Oct 24 06:34:48 2023] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-0.slice/session-17883.scope,task=mo-service,pid=3089545,uid=1000
[Tue Oct 24 06:34:48 2023] Out of memory: Killed process 3089545 (mo-service) total-vm:75756080kB, anon-rss:59683040kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:129232kB oom_score_adj:500
[Tue Oct 24 06:34:50 2023] systemd[1]: Started Session 22810 of user root.
[Tue Oct 24 06:34:50 2023] systemd[1]: session-22810.scope: Succeeded.

profile:
[oom_profile.tar.gz](https://github.com/matrixorigin/matrixone/files/13094133/oom_profile.tar.gz)

**Comment by volgariver6** [comment]
发现根本问题还是standalone模式下，磁盘IO问题导致的logservice写数据失败：

```
➜  12263 grep -irn "append to logservice took" mo-panic.log
mo-panic.log:34849:{"level":"WARN","time":"2023/10/21 23:50:12.042811 +0800","caller":"logservicedriver/appender.go:123","msg":"append to logservice took 17m17.61876962s"}
mo-panic.log:34893:{"level":"WARN","time":"2023/10/21 23:50:12.269330 +0800","caller":"logservicedriver/appender.go:123","msg":"append to logservice took 17m17.796237822s"}
mo-panic.log:34894:{"level":"WARN","time":"2023/10/21 23:50:12.269351 +0800","caller":"logservicedriver/appender.go:123","msg":"append to logservice took 17m17.824932845s"}
mo-panic.log:34895:{"level":"WARN","time":"2023/10/21 23:50:12.269405 +0800","caller":"logservicedriver/appender.go:123","msg":"append to logservice took 17m17.716395308s"}
mo-panic.log:34896:{"level":"WARN","time":"2023/10/21 23:50:12.269402 +0800","caller":"logservicedriver/appender.go:123","msg":"append to logservice took 17m17.775781625s"}
```

之前有一个issue记录了磁盘IO的异常数据：https://github.com/matrixorigin/matrixone/issues/9883

目前相关的问题：https://github.com/matrixorigin/matrixone/issues/12221

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
not fixed, @volgariver6 as discussed offline, reassign this issue to you

**Comment by volgariver6** [comment]
OOM issue dep with #11945

**Comment by volgariver6** [comment]
cn OOM issue, no progress

**Comment by aressu1985** [comment]
和刘博沟通，这个需要等莫尘Cache的PR合并，DEALY 1.2版本解决

**Comment by volgariver6** [comment]
no progress

**Comment by volgariver6** [comment]
oom 问题，没有进展

**Comment by volgariver6** [comment]
oom 问题，没有进展

**Comment by volgariver6** [comment]
cn service not ready 的问题已经修复，现在主要是 cn oom问题了。@nnsgmsone 帮忙处理一下

**Comment by nnsgmsone** [comment]
wait https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
正在和存储的同事协商https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
内存问题等待#12532

**Comment by nnsgmsone** [comment]
内存问题等待https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
内存问题等待https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
内存问题等待https://github.com/matrixorigin/matrixone/issues/12532

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
no process

**Comment by nnsgmsone** [comment]
等待pr合入

**Comment by nnsgmsone** [comment]
等待pr合ru

**Comment by nnsgmsone** [comment]
等待pr和入

**Comment by nnsgmsone** [comment]
处理事务泄露中

**Comment by nnsgmsone** [comment]
no process

**Comment by aressu1985** [comment]
fixed
