### ISSUE TITLE
[Bug]:  2 proxies were crashed by OOM during statbility test on distributed mode 

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#17757]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch Name

main

### Commit ID

e0d0d00

### Other Environment Information

```Markdown
- Hardware parameters:
3*CN: 16C 64G
1*DN: 16C 64G
3*LOG: 4C 16G
3*PROXY 3C 7G
- OS type:
- Others:
```

### Actual Behavior

2 proxies were crashed by OOM during statbility test on distributed mode 
<img width="723" alt="image" src="https://github.com/user-attachments/assets/9eff8d45-4d46-4f2e-acf4-bfb42646ca1e">

resource dashbaord:

https://shanghai.idc.matrixorigin.cn:30001/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-e0d0d00-202407262258&from=1722002230597&to=1722063021780

mo-log:
https://shanghai.idc.matrixorigin.cn:30001/explore?panes=%7B%227BO%22:%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22mo-e0d0d00-202407262258%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221722002230597%22,%22to%22:%221722063021780%22%7D%7D%7D&schemaVersion=1&orgId=1

### Steps to Reproduce

```Markdown
1. run a mo cluster with config in this issue
2. run tpch 10G loop test processes in one independant tenant
3. run tpcc 10 warehouse and 10 ternimals longrunnig test processes in one independant tenant, prepare mode
4. run sysbench mixed cases(insert/delete/update/select) longrunnig test processes with 75 terminals in one independant tenant,non-prepare mode
5. run another sysbench mixed cases(insert/delete/update/select) longrunnig test processe with  75 terminals in one independant tenant,non-prepare mode
```

**Comment by volgariver6** [comment]
从日志看不出来问题，需要在环境中加上proxy的heap profile，麻烦 @guguducken 配置一下

**Comment by volgariver6** [comment]
改了配置，正在重新跑测试

**Comment by volgariver6** [comment]
还是有oom发生，需要主动的将heap导出来查看了。

**Comment by volgariver6** [comment]
正在跑测试

**Comment by volgariver6** [comment]
找到问题原因了，堆外内存使用之后没有释放。

1. 把debug端口映射到本地：
    ```
    kubectl -n mo-d73f1c2-202408031024 port-forward stability-regression-dis-proxy-mmn8n 6069:6060
    ```
2. 获取当前内存使用情况
    ```
    go tool pprof http://localhost:6069/debug/malloc
    ```

3. 运行 top 30 查看堆外内存使用

![image](https://github.com/user-attachments/assets/9b52789a-4e52-4d4f-9b76-6bd45da955ea)

4. 结合代码做分析，找到问题，主要是 frontend.NewIOSession() 方法中申请的对外内存没有释放。解决办法是在 proxy 的 client conn 和server conn close 方法中释放内存。

**Comment by volgariver6** [comment]
fixed

**Comment by aressu1985** [comment]
not fixed

commit: c1c365c99feead9f1e021c7a2e26e707c31be04e

<img width="613" alt="image" src="https://github.com/user-attachments/assets/f4ef8143-b23f-4a25-aaa5-aaabd067cef2">

<img width="1407" alt="image" src="https://github.com/user-attachments/assets/8df70314-9dc2-4475-8cd8-4007585855d5">

https://shanghai.idc.matrixorigin.cn:30001/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-c1c365c-202408062226&from=1722954611588&to=1722970862283

**Comment by volgariver6** [comment]
已提交新的pr修复

**Comment by volgariver6** [comment]
等待pr合并

**Comment by aressu1985** [comment]
问题尚未解决，需要继续查看

**Comment by xzxiong** [comment]
new case:
- namespace: mo-c2fa177-202408102118
- profile: [cn.heap.tgz](https://github.com/user-attachments/files/16577066/cn.heap.tgz), [proxy.heap.tgz](https://github.com/user-attachments/files/16577068/proxy.heap.tgz)

https://shanghai.idc.matrixorigin.cn:30001/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-c2fa177-202408102118&from=now-24h&to=now&refresh=10s

![企业微信截图_722c4e20-ac76-40ac-8fee-24c4589ae5dc](https://github.com/user-attachments/assets/478f459d-b3f1-47d4-9321-fa28fbe4a91c)

**Comment by xzxiong** [comment]
> new case:
> 
> * namespace: mo-c2fa177-202408102118
> * profile: [cn.heap.tgz](https://github.com/user-attachments/files/16577066/cn.heap.tgz), [proxy.heap.tgz](https://github.com/user-attachments/files/16577068/proxy.heap.tgz)
> 
> https://shanghai.idc.matrixorigin.cn:30001/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-c2fa177-202408102118&from=now-24h&to=now&refresh=10s
> 
> ![企业微信截图_722c4e20-ac76-40ac-8fee-24c4589ae5dc](https://private-user-images.githubusercontent.com/3927687/356927527-478f459d-b3f1-47d4-9321-fa28fbe4a91c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTk5MDQsIm5iZiI6MTcyMzQ1OTYwNCwicGF0aCI6Ii8zOTI3Njg3LzM1NjkyNzUyNy00NzhmNDU5ZC1iM2YxLTQ3ZDQtOTMyMS1mYTI4ZmJlNGE5MWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMTA0NjQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmI1YjZjMTc4MjU1MWJiMmI5MTAyMjQ2YWU5NGYyMzVjNjUxMmIwOTgyNjAxNTg0MzQxMTg1ZTRhMjY2ODJmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zaG_rthJGyh8pxuFy-Ux7RVeBuIoPBzzy5Mzdw8DXQM)

针对该问题，增加 meric 进行观测，基本确定：
- 由于写 sql 失败（并且延迟大），导致mometric 的请求堆积，导致申请过多内存
> debug 代码, https://github.com/xzxiong/matrixone/tree/5243eadcbcc94399b26120e238f237d97a6e38b6
![image](https://github.com/user-attachments/assets/96bfe3e6-2923-4ab4-8a87-2546d708c46b)

**Comment by xzxiong** [comment]
> > new case:
> > 
> > * namespace: mo-c2fa177-202408102118
> > * profile: [cn.heap.tgz](https://github.com/user-attachments/files/16577066/cn.heap.tgz), [proxy.heap.tgz](https://github.com/user-attachments/files/16577068/proxy.heap.tgz)
> > 
> > https://shanghai.idc.matrixorigin.cn:30001/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?orgId=1&var-datasource=prometheus&var-cluster=&var-namespace=mo-c2fa177-202408102118&from=now-24h&to=now&refresh=10s
> > [image] ...
> 
> 针对该问题，增加 meric 进行观测，基本确定：
> 
> * 由于写 sql 失败（并且延迟大），导致mometric 的请求堆积，导致申请过多内存
> * 如下图，Collector queue 中 metric 的队列一直在增长。（dashboard: `Trace Metric`)
> 
> > debug 代码, https://github.com/xzxiong/matrixone/tree/5243eadcbcc94399b26120e238f237d97a6e38b6
> > [image] ...

#18081 针对这里 metric req 堆积的问题，增加 backoff 策略：当metric queue 中请求数操作 > 8 (根据配置计算）时，跳过 sql flush的操作，直接执行 csv flush

**Comment by volgariver6** [comment]
#18081 已经提交处理OOM的问题

#18099 将 malloc 的heap文件也保存到etl中，如果再出现oom，再分析一下malloc的heap

**Comment by volgariver6** [comment]
找到最后泄漏的地方，提交pr修复

**Comment by volgariver6** [comment]
![image](https://github.com/user-attachments/assets/667b830d-a81c-43e6-87d4-33f9e50ee692)
proxy 运行内存zhan占用平稳，没有泄漏了

**Comment by aressu1985** [comment]
fixed
