### ISSUE TITLE
[Bug]: Duplicate Operation in mo-cluster

### ISSUE THREAD

**Issue by sukki37** [matrixorigin/matrixone#5417]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):60e6d323b36ce7c288cf439537fe134ced928e5b
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

1. Duplicate database and db.table existed in one mo cluster：
2. System databases have been initialized twice
3. Any SQL seems to be executing twice

![image](https://user-images.githubusercontent.com/77312370/194461644-d7060f69-29b3-456a-ac81-c35704ef971d.png)
![image](https://user-images.githubusercontent.com/77312370/194461746-d0e35490-5846-406d-9fb2-6a31fa966459.png)

### Steps to Reproduce

```Markdown
start a mo-cluster with mo-operator.
```

**Comment by daviszhen** [comment]
i think the transaction may have bugs.

**Comment by reusee** [comment]
fixed in https://github.com/matrixorigin/matrixone/pull/5421

**Comment by aylei** [comment]
This issue is still observed in https://github.com/matrixorigin/matrixone/commit/724c8affc1cc45e72a734248150a95a7ff3cbdd3

@reusee

**Comment by sukki37** [comment]
update, This issue is still observed in the `43446ad2` commit. @reusee

**Comment by sukki37** [comment]
multi-cn has not been tested yet

**Comment by sukki37** [comment]
test pass with `92439b1d3f73552ca912de6180099821c39955fd`

overall configuration: 2 tpcn, 1 dn, 3 logservice with s3 enabled
