### ISSUE TITLE
[Bug]: insert into select reported duplicate message is error

### ISSUE THREAD

**Issue by heni02** [matrixorigin/matrixone#6261]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.6.0 or 8b23a93):4c8db53d269039cb235330f1a8e968f444134374
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

insert into select reported duplicate message is error
![image](https://user-images.githubusercontent.com/113406637/199898128-35410d34-166a-489f-b2b4-639f959210a2.png)

### Expected Behavior

tae data: duplicate

### Steps to Reproduce

create external table ex_table_cpk(clo1 tinyint,clo2 smallint,clo3 int,clo4 bigint,clo5 tinyint unsigned,clo6 smallint unsigned,clo7 int unsigned,clo8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255))infile{"filepath"='$resources/external_table_file/cpk_table_1.csv'} ;

create  table  cpk_table_3_pk(col1 tinyint,col2 smallint,col3 int,col4 bigint,col5 tinyint unsigned,col6 smallint unsigned,col7 int unsigned,col8 bigint unsigned,col9 float,col10 double,col11 varchar(255),col12 Date,col13 DateTime,col14 timestamp,col15 bool,col16 decimal(5,2),col17 text,col18 varchar(255),col19 varchar(255),col20 varchar(255),primary key(col2,col9,col14,col19));

insert into cpk_table_3_pk select * from ex_table_cpk;

**Comment by XuPeng-SH** [comment]
Right now we report detailed duplicated info on duplication errors. I think it is better to change the bvt result

**Comment by XuPeng-SH** [comment]
What is the expected result?

**Comment by domingozhang** [comment]
`tae data: duplicate`
this is fine

**Comment by qingxinhome** [comment]
not working on it

**Comment by qingxinhome** [comment]
The problem has been resolved in the Yuanning branch, as shown in the figure: @heni02 
![image](https://github.com/matrixorigin/matrixone/assets/70939751/567f8574-d0d1-4561-b28e-8f63ca234dd5)

**Comment by qingxinhome** [comment]
The problem should has been resolved , please test it @heni02

**Comment by heni02** [comment]
same as #7413

**Comment by heni02** [comment]
now Pessimistic mode resolve this issue, but optimistic mode problem still exists:
![image](https://github.com/matrixorigin/matrixone/assets/113406637/6d3d380a-cf0c-4841-823c-ef96116f2b50)

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.

**Comment by heni02** [comment]
去除tag，还是有相同问题出现@qingxinhome
<img width="1149" alt="企业微信截图_03060d9e-f592-4bdf-9409-46e0be5d4b2d" src="https://github.com/matrixorigin/matrixone/assets/113406637/042d9662-dfd6-473a-b72d-70ef2d9313c4">

**Comment by qingxinhome** [comment]
delay

**Comment by qingxinhome** [comment]
delay

**Comment by qingxinhome** [comment]
Pending processing

**Comment by fengttt** [comment]
Please check if this one is still relevant.

**Comment by Cabbage74** [comment]
The duplicate message has now been detailed as follows:  
Duplicate entry '(20,7.2914,1985-01-12 23:59:59,r@sina.com)' for key '(col2,col9,col14,col19)'

Refer to the attached screenshot for complete BVT results:
![Image](https://github.com/user-attachments/assets/bb1b5fd8-e989-43dd-b42a-c6173c3c9fed)

**Comment by heni02** [comment]
confirm，closed

**Comment by matrix-meow** [comment]
Hello @heni02. The bug issue in the BVT test code has not been removed,issues automatically open.
