### ISSUE TITLE
[Bug]: MO crash by invalid memory address or nil pointer dereference when run oltp delete high concurrency test with push mode

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#8303]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):751c307e8ab4c25812de9250778d342ad1ffc5c2
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

error log:
2023/03/08 07:47:30.133704 +0800 INFO frontend/util.go:404 query trace status {"connection_id": 7611, "statement": "show tables", "status": "success", "span": {"trace_id": "6c54092a-bd42-11ed-a363-b07b25f8b524", "kind": "statement"}, "session_info": "connectionId 7611"}
2023/03/08 07:47:30.133743 +0800 INFO frontend/util.go:404 query trace {"connection_id": 7611, "query": "select \n    \t\t\t\t\t\tcron_task_id,\n    \t\t\t\t\t\ttask_metadata_id,\n    \t\t\t\t\t\ttask_metadata_executor,\n    \t\t\t\t\t\ttask_metadata_context,\n    \t\t\t\t\t\ttask_metadata_option,\n    \t\t\t\t\t\tcron_expr,\n    \t\t\t\t\t\tnext_time,\n    \t\t\t\t\t\ttrigger_times,\n    \t\t\t\t\t\tcreate_at,\n    \t\t\t\t\t\tupdate_at\n\t\t\t\t\t\tfrom mo_task.sys_cron_task", "session_info": "connectionId 7611"}
2023/03/08 07:47:30.136944 +0800 ERROR frontend/mysql_cmd_executor.go:4043 error: internal error: panic runtime error: invalid memory address or nil pointer dereference:
runtime.panicmem
        /usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:835
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnDatabase).Relation
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_database.go:125
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).getRelation
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1879
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Resolve
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1936
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1756
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1880
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1860
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildFrom
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1642
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1264
github.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/build.go:28
github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/build.go:59
github.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/optimize.go:56
github.com/matrixorigin/matrixone/pkg/frontend.buildPlan
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:2313
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile
data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:2062
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3517
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4068
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:175
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:320
github.com/fagongzi/goetty/v2.(*server).doConnection
        /home/github/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
        /home/github/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1594 {"span": {"trace_id": "6c53bf76-bd42-11ed-a363-b07b25f8b524", "kind": "session"}}
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4043
runtime.gopanic
        /usr/local/go/src/runtime/panic.go:884
runtime.panicmem
        /usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:835
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnDatabase).Relation
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_database.go:125
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).getRelation
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1879
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Resolve
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1936
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1756
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1880
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1860
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildSelect
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1264
github.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/build.go:28
github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/build.go:59
github.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/optimize.go:56
github.com/matrixorigin/matrixone/pkg/frontend.buildPlan
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:2313
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:2062
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3517
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:4068
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:175
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:320
github.com/fagongzi/goetty/v2.(*server).doConnection
        /home/github/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
        /home/github/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
2023/03/08 07:47:30.137018 +0800 ERROR frontend/util.go:429 rt execute request failed. error:internal error: panic runtime error: invalid memory address or nil pointer dereference:
runtime.panicmem
        /usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:835
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnDatabase).Relation
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_database.go:125
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).getRelation
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1879

**Comment by m-schen** [comment]
push model has bug now, multi cn test (docker compose) can reproduce it easily.
do a more verify after we fixed it.

**Comment by m-schen** [comment]
please try it again. because we fix a message bug at pr https://github.com/matrixorigin/matrixone/pull/8378.

**Comment by aressu1985** [comment]
this issue is not fixed

it happened again on 3.17 regression in push mode, but this time  during point select test:

2023/03/17 05:52:33.129655 +0800 INFO logtail/handle.go:545 [Logtail] send block meta for "sbtest9"
2023/03/17 05:52:33.129628 +0800 ERROR frontend/mysql_cmd_executor.go:3678 error: internal error: panic runtime error: invalid memory address or nil pointer dereference:
runtime.panicmem
        /usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
        /usr/local/go/src/runtime/signal_unix.go:835
github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailClient).Subscribe
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/logtail/service/client.go:78
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*logTailSubscriber).subscribeTable
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/logtailPushModel.go:229
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).tryToGetTableLogTail
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/logtailPushModel.go:331
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).UpdateOfPush
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/db.go:321
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).updateMeta
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_table_meta.go:55
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Stats
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_table.go:43
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Stats
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:2390
github.com/matrixorigin/matrixone/pkg/sql/plan.ReCalcNodeStats
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/stats.go:247
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).appendNode
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1635
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1849
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1879
github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1859
github.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/build.go:28
github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/build.go:59
github.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/optimize.go:56
github.com/matrixorigin/matrixone/pkg/frontend.buildPlan
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:1910
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:1659
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3144
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3703
github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:175
github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:320
github.com/fagongzi/goetty/v2.(*server).doConnection
        /home/github/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381
github.com/fagongzi/goetty/v2.(*server).doStart.func2.1
        /home/github/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1594 {"span": {"trace_id": "dabef39d-c444-11ed-a312-b07b25f8b524", "kind": "session"}}
github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1
        /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3678
runtime.gopanic

**Comment by m-schen** [comment]
明天统一开始处理push的bug.

**Comment by m-schen** [comment]
I have fix the reconnect race at #8725

**Comment by jiangxinmeng1** [comment]
跑sysbench重启的时候复现了，但复现的概率很低，只遇到了一次。

commit: 0839a0dd467d5dc
复现步骤：
1. 启动mo-service，用mo-load跑sysbench/mixed_10_100000
2. 20min后重启mo-service
3. 当mysql客户端去连接的时候，mo-service会报issue里的panic

**Comment by m-schen** [comment]
还没定位到问题。

**Comment by m-schen** [comment]
didn't find source reason.

**Comment by m-schen** [comment]
> this issue is not fixed
> 
> it happened again on 3.17 regression in push mode, but this time during point select test:
> 
> 2023/03/17 05:52:33.129655 +0800 INFO logtail/handle.go:545 [Logtail] send block meta for "sbtest9" 2023/03/17 05:52:33.129628 +0800 ERROR frontend/mysql_cmd_executor.go:3678 error: internal error: panic runtime error: invalid memory address or nil pointer dereference: runtime.panicmem /usr/local/go/src/runtime/panic.go:260 runtime.sigpanic /usr/local/go/src/runtime/signal_unix.go:835 github.com/matrixorigin/matrixone/pkg/vm/engine/tae/logtail/service.(*LogtailClient).Subscribe /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/tae/logtail/service/client.go:78 github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*logTailSubscriber).subscribeTable /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/logtailPushModel.go:229 github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).tryToGetTableLogTail /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/logtailPushModel.go:331 github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*Engine).UpdateOfPush /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/db.go:321 github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).updateMeta /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_table_meta.go:55 github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnTable).Stats /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_table.go:43 github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Stats /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:2390 github.com/matrixorigin/matrixone/pkg/sql/plan.ReCalcNodeStats /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/stats.go:247 github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).appendNode /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1635 github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1849 github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1879 github.com/matrixorigin/matrixone/pkg/sql/plan.(*QueryBuilder).buildTable /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/query_builder.go:1859 github.com/matrixorigin/matrixone/pkg/sql/plan.runBuildSelectByBinder /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/build.go:28 github.com/matrixorigin/matrixone/pkg/sql/plan.BuildPlan /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/build.go:59 github.com/matrixorigin/matrixone/pkg/sql/plan.(*BaseOptimizer).Optimize /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/sql/plan/optimize.go:56 github.com/matrixorigin/matrixone/pkg/frontend.buildPlan /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:1910 github.com/matrixorigin/matrixone/pkg/frontend.(*TxnComputationWrapper).Compile /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:1659 github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).doComQuery /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3144 github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3703 github.com/matrixorigin/matrixone/pkg/frontend.(*Routine).handleRequest /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine.go:175 github.com/matrixorigin/matrixone/pkg/frontend.(*RoutineManager).Handler /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/routine_manager.go:320 github.com/fagongzi/goetty/v2.(*server).doConnection /home/github/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:381 github.com/fagongzi/goetty/v2.(*server).doStart.func2.1 /home/github/go/pkg/mod/github.com/fagongzi/goetty/v2@v2.0.3-0.20221212132037-abf2d4c05484/application.go:344 runtime.goexit /usr/local/go/src/runtime/asm_amd64.s:1594 {"span": {"trace_id": "dabef39d-c444-11ed-a312-b07b25f8b524", "kind": "session"}} github.com/matrixorigin/matrixone/pkg/frontend.(*MysqlCmdExecutor).ExecRequest.func1 /data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/mysql_cmd_executor.go:3678 runtime.gopanic

it's not related to this issue.

**Comment by m-schen** [comment]
The sort method on the cn end for UpdateResponse is unstable sorting.
I may make `insert delete` to be `delete insert`,  it will cause data lost or data more.

I will fixed the bug.

**Comment by m-schen** [comment]
fix a unstable sort error will cause wrong result. and can verify it if the pr was merged.

**Comment by m-schen** [comment]
可以验证一下是否还会出现以下的错误，如果不会的话便是修复了。

```
2023/03/08 07:47:30.136944 +0800 ERROR frontend/mysql_cmd_executor.go:4043 error: internal error: panic runtime error: invalid memory address or nil pointer dereference:
runtime.panicmem
/usr/local/go/src/runtime/panic.go:260
runtime.sigpanic
/usr/local/go/src/runtime/signal_unix.go:835
github.com/matrixorigin/matrixone/pkg/vm/engine/disttae.(*txnDatabase).Relation
/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/vm/engine/disttae/txn_database.go:125
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).getRelation
/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1879
github.com/matrixorigin/matrixone/pkg/frontend.(*TxnCompilerContext).Resolve
/data1/action-runner/_work/mo-nightly-regression/mo-nightly-regression/head/pkg/frontend/session.go:1936
```

**Comment by aressu1985** [comment]
fixed: f0d52530f
