### ISSUE TITLE
[Bug]: Set sql_mode using set global sql_mode='xxx' does not take effect after mo-service's restarted

### ISSUE THREAD

**Issue by aronchanisme** [matrixorigin/matrixone#9689]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):

commit 65c0f0d8cbbf445cd24e729400303098a346de19 (HEAD -> main, origin/main, origin/HEAD)
Author: fagongzi <zhangxu19830126@gmail.com>
Date:   Thu May 25 22:23:48 2023 +0800

- Hardware parameters: 10c 16g
- OS type: mac os 
- Others:
```
uname -a 
Darwin momac.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64
```
```

### Actual Behavior

Set sql_mode using set global sql_mode='xxx' does not take effect after mo-service's restarted

1. Change the sql_mode by `set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'`, check the sql_mode again by `select @@sql_mode`, and it only takes effect when I re-connect mo. This works as expected, and as the same behavior as in mysql.
<img width="1224" alt="企业微信截图_a683fb3b-83bb-4149-a268-051479cb3b59" src="https://github.com/matrixorigin/matrixone/assets/46433151/c589c73e-47f9-4110-8f73-43a4e0b57b1d">
<img width="1268" alt="企业微信截图_ebe6f664-e8ef-45d6-9b9d-6f121fb64c2d" src="https://github.com/matrixorigin/matrixone/assets/46433151/4878b08b-98ad-453d-a740-474d0fc1d1e0">

2. Restart mo-service, and check sql_mode again, but it was reverted back to what it was before it was changed.
<img width="1632" alt="企业微信截图_54449792-27da-410a-8b44-a1ed671e60ec" src="https://github.com/matrixorigin/matrixone/assets/46433151/751d0f04-ee68-4505-b174-b571c4ac341a">

### Expected Behavior

When a `set gloabl xxx=xxx` command is executed successfully, even if mo-service is restarted, the setting value should remain the same as what it is changed.

### Steps to Reproduce

```Markdown
mysql> select @@sql_mode
    -> ;
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
    -> ;
Query OK, 0 rows affected (0.01 sec)

mysql> select @@sql_mode;
+----------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                         |
+----------------------------------------------------------------------------------------------------+
| ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_TRANS_TABLES |
+----------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> exit
Bye


~/mo6001
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 210
Server version: 8.0.30-MatrixOne-v0.7.0 MatrixOne

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select @@sql_mode;
+----------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                         |
+----------------------------------------------------------------------------------------------------+
| ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_TRANS_TABLES |
+----------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

emysql> exit
Bye

xx@xx matrixone % ps -ef |grep mo-service
  501 81851     1   0  3:05PM ??         2:25.30 ./mo-service -daemon -launch ./etc/launch-tae-CN-tae-DN/launch.toml -debug-http :9876
  501 81989 79235   0  3:21PM ttys000    0:00.00 grep --color=auto mo-service
xx@xx matrixone % kill 81851
xx@xx matrixone % ps -ef |grep mo-service
  501 81994 79235   0  3:21PM ttys000    0:00.00 grep --color=auto mo-service
xx@xx matrixone % ps -ef |grep mo-service
  501 81994 79235   0  3:21PM ttys000    0:00.00 grep --color=auto mo-service
xx@xx matrixone % ./mo-service -daemon -launch ./etc/launch-tae-CN-tae-DN/launch.toml -debug-http :9876 >./logs/stdout-20230526-152138.log 2>./logs/stderr-20230526-152138.log 
xx@xx matrixone % 
xx@xx matrixone % ps -ef |grep mo-service                                                                                                                                      
  501 81996     1   0  3:21PM ??         0:00.41 ./mo-service -daemon -launch ./etc/launch-tae-CN-tae-DN/launch.toml -debug-http :9876
  501 82001 79235   0  3:21PM ttys000    0:00.00 grep --color=auto mo-service
xx@xx matrixone % ~/mo6001
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 315
Server version: 8.0.30-MatrixOne-v0.7.0 MatrixOne

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select @@sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

### Additional information

pls see feature request: https://github.com/matrixorigin/matrixone/issues/9082

**Comment by YANGGMM** [comment]
have find the reason, will fix it soon

**Comment by YANGGMM** [comment]
have fixed in https://github.com/matrixorigin/matrixone/commit/427fc57cf0370ce52623d85ea4334047e6d6a710

**Comment by aronchanisme** [comment]
Issue remains when below steps are taken

```bash
git clone xxx
make build
# note the way to start mo-service, -daemon is to keep mo-service running as daemon service, i.e., in background mode
/data/xxx/mo_ins/20230530_233801/matrixone//mo-service -debug-http :9876 -daemon -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -udump -p111 -P6001 -h127.0.0.1

select @@sql_mode
set global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

exit
# reconnect, it takes effect
mysql -udump -p111 -P6001 -h127.0.0.1
select @@sql_mode

# kill mo-service, but dont give -9 signal
ps -ef |grep mo-service
kill xxxx(pid)

# restart mo-service
/data/xxx/mo_ins/20230530_233801/matrixone//mo-service -debug-http :9876 -daemon -launch ./etc/launch-tae-CN-tae-DN/launch.toml
mysql -udump -p111 -P6001 -h127.0.0.1
select @@sql_mode
```

<img width="1642" alt="企业微信截图_8c0678b6-439b-4f02-be67-b4d98a1ff4df" src="https://github.com/matrixorigin/matrixone/assets/46433151/09087746-c727-473e-b252-61609ab944cf">

<img width="1708" alt="企业微信截图_65d0941c-c978-4bdb-bfff-6c480278c009" src="https://github.com/matrixorigin/matrixone/assets/46433151/b9fa2be3-cec5-481e-a2e2-e8b87eb2a1de">

**Comment by aronchanisme** [comment]
This issue can be reproduced on a specific server, but it can't while on another server. Seems very strange to me. Will it be raised by mysql client version? Not sure... Need to analyze it further.
<img width="1080" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/73ec6a3b-5c18-4ecc-b590-b1e7206481ec">
<img width="1608" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/ad348bc9-f501-4157-b1b6-a9b894649228">
<img width="1183" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/c42be060-7c86-466a-b40a-1c77743ae636">
<img width="824" alt="image" src="https://github.com/matrixorigin/matrixone/assets/46433151/44a959dd-f432-4a8e-b925-b4eef82cb5b4">

**Comment by aronchanisme** [comment]
Please kindly help confirm and revert back to me when it's really resolved @YANGGMM

**Comment by YANGGMM** [comment]
无法复现

**Comment by YANGGMM** [comment]
无法复现，麻烦清除数据之后再测试一下 @aronchanisme ，有问题麻烦再找我一下

**Comment by aronchanisme** [comment]
Confirmed fixed. Now changed sql_mode in account 1, will not have any effect on account 2. And sql_mode is changed as expected after account 1 re-logined. After mo-service is restarted, sql_mode is also in changed state in account 1, as expected. And sql_mode remains as default in account 2, as expected.

Test commit id:
```bash
mo_ctl get_cid                                          6.1s  2023-07-15T16:33:572023-07-15_16:37:45.204    [INFO]    Try get mo commit id
commit 0e824dc09cefe7e356f149c97623d24c3ff7da42
Author: nnsgmsone <nnsmgsone@outlook.com>
Date:   Sat Jul 15 16:21:42 2023 +0800

    Fix statement out-of-bounds within workspace (#10686)
    
2023-07-15_16:37:45.212    [INFO]    Get commit id succeeded
```

Test record:
```bash
 $  root@VM-0-12-centos  /m/v/d/c/s/data_insert  mysql -uacc_1:root -p111 -P6001 -h127.0.0.1             1.1m  2023-07-15T16:28:10mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10
Server version: 8.0.30-MatrixOne-v0.8.0 MatrixOne

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select current_user;
+--------------------+
| current_user()     |
+--------------------+
| acc_1:root@0.0.0.0 |
+--------------------+
1 row in set (0.00 sec)

mysql> select * from mo_catalog.mo_role;
+---------+--------------+---------+-------+---------------------+----------+
| role_id | role_name    | creator | owner | created_time        | comments |
+---------+--------------+---------+-------+---------------------+----------+
|       2 | accountadmin |       2 |     2 | 2023-07-15 08:27:04 |          |
|       1 | public       |       2 |     2 | 2023-07-15 08:27:04 |          |
+---------+--------------+---------+-------+---------------------+----------+
2 rows in set (0.01 sec)

mysql> select @@sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> set global sql_mode=ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_TRANS_TABLES 
    -> ;
ERROR 1064 (HY000): SQL parser error: You have an error in your SQL syntax; check the manual that corresponds to your MatrixOne server version for the right syntax to use. syntax error at line 1 column 70 near ",NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_TRANS_TABLES";
mysql> set global sql_mode="ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_TRANS_TABLES"
    -> ;
Query OK, 0 rows affected (0.01 sec)

mysql> select @@sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> exit
Bye
 $  root@VM-0-12-centos  /m/v/d/c/s/data_insert  mysql -uacc_1:root -p111 -P6001 -h127.0.0.1               1m  2023-07-15T16:29:18mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 11
Server version: 8.0.30-MatrixOne-v0.8.0 MatrixOne

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select current_user;
+--------------------+
| current_user()     |
+--------------------+
| acc_1:root@0.0.0.0 |
+--------------------+
1 row in set (0.00 sec)

mysql> select @@sql_mode;
+----------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                         |
+----------------------------------------------------------------------------------------------------+
| ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_TRANS_TABLES |
+----------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> exit
Bye
 $  root@VM-0-12-centos  /m/v/d/c/s/data_insert  mysql -uacc_2:root -p111 -P6001 -h127.0.0.1            18.3s  2023-07-15T16:29:37mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 12
Server version: 8.0.30-MatrixOne-v0.8.0 MatrixOne

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select @@sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> exit
Bye
 $  root@VM-0-12-centos  /m/v/d/c/s/data_insert                                                          9.4s  2023-07-15T16:30:05 $  root@VM-0-12-centos  /m/v/d/c/s/data_insert  mo_ctl get_cid                                          9.4s  2023-07-15T16:31:272023-07-15_16:31:30.684    [INFO]    Try get mo commit id
commit 0e824dc09cefe7e356f149c97623d24c3ff7da42
Author: nnsgmsone <nnsmgsone@outlook.com>
Date:   Sat Jul 15 16:21:42 2023 +0800

    Fix statement out-of-bounds within workspace (#10686)
    
2023-07-15_16:31:30.692    [INFO]    Get commit id succeeded
 $  root@VM-0-12-centos  /m/v/d/c/s/data_insert  mo_ctl restart                                                 2023-07-15T16:31:302023-07-15_16:33:24.855    [INFO]    At least one mo-service is running. Process info: 
root     1775987       1 10 16:25 ?        00:00:50 /data/xxx/mo_ins/20230715_1622/matrixone/mo-service -daemon -debug-http :9876 -launch /data/xxx/mo_ins/20230715_1622/matrixone/etc/launch-tae-CN-tae-DN/launch.toml
2023-07-15_16:33:24.858    [INFO]    List of pid(s): 
1775987
2023-07-15_16:33:24.860    [INFO]    Try stop all mo-services found for a maximum of 10 times, try no: 1
2023-07-15_16:33:24.863    [INFO]    Stopping mo-service with pid 1775987 with command: kill  1775987
2023-07-15_16:33:24.866    [INFO]    kill succeeded
2023-07-15_16:33:24.868    [INFO]    Wait for 5 seconds
2023-07-15_16:33:29.894    [INFO]    No mo-service is running
2023-07-15_16:33:29.897    [INFO]    Stop succeeded
2023-07-15_16:33:29.899    [INFO]    Wait for 2 seconds
2023-07-15_16:33:31.926    [INFO]    No mo-service is running
2023-07-15_16:33:31.930    [INFO]    Starting mo-service: cd /data/xxx/mo_ins/20230715_1622/matrixone/ && /data/xxx/mo_ins/20230715_1622/matrixone/mo-service -daemon -debug-http :9876 -launch /data/xxx/mo_ins/20230715_1622/matrixone/etc/launch-tae-CN-tae-DN/launch.toml >/data/xxx/mo_ins/20230715_1622/matrixone/logs/stdout-20230715_163331.log 2>/data/xxx/mo_ins/20230715_1622/matrixone/logs/stderr-20230715_163331.log
2023-07-15_16:33:31.953    [INFO]    Wait for 2 seconds
2023-07-15_16:33:33.980    [INFO]    At least one mo-service is running. Process info: 
root     1779986       1  5 16:33 ?        00:00:00 /data/xxx/mo_ins/20230715_1622/matrixone/mo-service -daemon -debug-http :9876 -launch /data/xxx/mo_ins/20230715_1622/matrixone/etc/launch-tae-CN-tae-DN/launch.toml
2023-07-15_16:33:33.983    [INFO]    List of pid(s): 
1779986
2023-07-15_16:33:33.985    [INFO]    Start succeeded
 $  root@VM-0-12-centos  /m/v/d/c/s/data_insert  mysql -uacc_1:root -p111 -P6001 -h127.0.0.1             9.2s  2023-07-15T16:33:34mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 103
Server version: 8.0.30-MatrixOne-v0.8.0 MatrixOne

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select @@sql_mode;
+----------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                         |
+----------------------------------------------------------------------------------------------------+
| ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,STRICT_TRANS_TABLES |
+----------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> exit
Bye
 $  root@VM-0-12-centos  /m/v/d/c/s/data_insert  mysql -uacc_2:root -p111 -P6001 -h127.0.0.1            10.2s  2023-07-15T16:33:48mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 109
Server version: 8.0.30-MatrixOne-v0.8.0 MatrixOne

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select @@sql_mode;
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES |
+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> exit
Bye
```
