### ISSUE TITLE
[Bug]: cn panic after dn oom during tpcc 10-100 test on eks with 3*cn and 1*dn

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9949]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-29f1e83
- Hardware parameters:
  3*CN: 16C 64G
  1*DN: 16C 64G
  3*LOG: 4C 8G
- OS type:
- Others:
  DISK CACHE: 100G
  MEM CACHE: 12G
```

### Actual Behavior

The test tools:
<img width="1357" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/4fd7cd52-613a-4973-936d-0830cb6a0bc2">

the pod status:
<img width="602" alt="image" src="https://github.com/matrixorigin/matrixone/assets/47846308/da9a65ba-89b3-451d-9ef8-974289b598ce">

dn syslog:
[Thu Jun  8 12:53:37 2023] [   2910] 65534  2910   180115     5155   143360        0          1000 node_exporter
[Thu Jun  8 12:53:37 2023] [   3845] 10001  3845      189        1    36864        0          -998 pause
[Thu Jun  8 12:53:37 2023] [   5272] 10001  5272   184995     7770   163840        0          1000 loki-canary
[Thu Jun  8 12:53:37 2023] [   3846]     0  3846      189        1    36864        0          -998 pause
[Thu Jun  8 12:53:37 2023] [   5269]     0  5269    94978    12140   315392        0          1000 fluent-bit
[Thu Jun  8 12:53:37 2023] [   4074]     0  4074      189        1    36864        0          -998 pause
[Thu Jun  8 12:53:37 2023] [   5270]     0  5270   541631    17867   454656        0          1000 promtail
[Thu Jun  8 12:53:37 2023] [   4289]     0  4289      189        1    36864        0          -998 pause
[Thu Jun  8 12:53:37 2023] [   5271]     0  5271   178689     2732   110592        0          1000 prometheus-conf
[Thu Jun  8 12:53:37 2023] [   5748]     0  5748   623853    26387   589824        0          1000 agent
[Thu Jun  8 12:53:37 2023] [  27926]     0 27926      189        1    36864        0          -998 pause
[Thu Jun  8 12:53:37 2023] [  28056]     0 28056      967      724    45056        0          1000 bash
[Thu Jun  8 12:53:37 2023] [  31210]     0 31210     1033      854    45056        0          1000 bash
[Thu Jun  8 12:53:37 2023] [  23285]     0 23285      550      196    40960        0          1000 sleep
[Thu Jun  8 12:53:37 2023] [   6459]     0  6459      189        1    36864        0          -998 pause
[Thu Jun  8 12:53:37 2023] [   6642]     0  6642   185425     8233   163840        0          1000 local-provision
[Thu Jun  8 12:53:37 2023] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=24d8e2e022b40a8c5f9e21ba6ffc19c5066554efb068b2bbbb30e5306170c639,mems_allowed=0,oom_memcg=/kubepods,task_memcg=/kubepods/burstable/podaa9a8b85-f465-4cde-9317-56a6905a713c/24d8e2e022b40a8c5f9e21ba6ffc19c5066554efb068b2bbbb30e5306170c639,task=mo-service,pid=16252,uid=0
[Thu Jun  8 12:53:37 2023] Memory cgroup out of memory: Killed process 16252 (mo-service) total-vm:63645056kB, anon-rss:60996684kB, file-rss:44112kB, shmem-rss:0kB, UID:0 pgtables:120232kB oom_score_adj:186
[Thu Jun  8 12:53:41 2023] oom_reaper: reaped process 16252 (mo-service), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

cn log:

[cn0-tpcc-panic.log](https://github.com/matrixorigin/matrixone/files/11688718/cn0-tpcc-panic.log)
[cn1-tpcc-panic.log](https://github.com/matrixorigin/matrixone/files/11688719/cn1-tpcc-panic.log)

### Steps to Reproduce

```Markdown
1.run a mo cluster on esk with 3cn use this config
2.run tpcc 10 warehouse 100 terminals test
```

**Comment by aressu1985** [comment]
the whole log is in : **s3://mo-ares/mo-benchmark/etl/**

**Comment by sukki37** [comment]
@XuPeng-SH pls help on repro on this issue

**Comment by XuPeng-SH** [comment]
#9953

**Comment by m-schen** [comment]
旧的比较逻辑是 （重连前cn已消费的log时间 >= 当前事务的开启时间）
这个逻辑有问题，如果在重连成功 -> 收到新的心跳期间有查询执行到这一步，可能会导致这个panic。

暂不确定，目前新代码不知道能不能复现这个bug。

**Comment by aptend** [comment]
repro branch: https://github.com/aptend/matrixone/tree/repro-9949

step:
```
1. ./mo-service -daemon -debug-http 127.0.0.1:8181 -launch etc/launch-tae-CN-tae-DN/launch.toml 2>&1
2. run tpcc
3. select enable_fault_injection(); select add_fault_point('cn-reconnect', ':::', 'echo', 0, 'xxx');
```

fix #9962 has been verified on this branch

**Comment by m-schen** [comment]
fixed.

**Comment by sukki37** [comment]
Not fixed, panic still occurred in many merge run tests.
one of them is https://github.com/matrixorigin/matrixone/actions/runs/5242223411

<img width="1534" alt="image" src="https://github.com/matrixorigin/matrixone/assets/77312370/236d05e5-ffe0-44ed-9b49-b26927ae0aaa">

**Comment by zhangxu19830126** [comment]
#10011，fix latestAppliedLogTailTS was reset to 0 in two consecutive failed reconnects.

**Comment by aressu1985** [comment]
fixed:nightly-d4d74e7
